name: Run PowerShell Script

on: 
  workflow_dispatch:
    inputs:
      param1:
        description: 'First parameter'
        required: true
        default: 'default_value1'
      param2:
        description: 'Second parameter'
        required: true
        default: 'default_value2'

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run PowerShell script
      run: |
        $param1 = ${{ github.event.inputs.param1 }}
        $param2 = ${{ github.event.inputs.param2 }}
        .\script.ps1 -Param1 $param1 -Param2 $param2
      shell: pwsh