name: Deploy reports

on: 
  workflow_dispatch:
    inputs:
      report:
        description: 'Report to deploy'
        required: true
        type: choice
        options:
          - Report1
          - Report2
      environments:
        description: 'Environments to deploy'
        required: true
        default: '["Tenant1", "Tenant2"]'
        type: string

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        environments: ${{ fromJson(inputs.environments) }}
        
    environment: ${{ matrix.environments }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Power BI Management Module
      run: |
        #Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        #Import-Module MicrosoftPowerBIMgmt
        write-host "skip the step"

    - name: Run PowerShell script
      env:
        JSON_SECRETS: ${{ toJSON(secrets) }}
        JSON_PARAM1: ${{ vars.PARAM1 }}
        JSON_ENV: ${{ toJSON(matrix.environments) }}
        JSON_MATRIX: ${{ toJSON(matrix) }}
      run: |
        $param1 = $env:JSON_PARAM1
        $param2 = $env:JSON_DOC
        $param3 = $env:JSON_ENV
        $param4 = $env:JSON_MATRIX
        .\DeployScript\script.ps1 -Param1 $param1 -Param2 $param2 -Param3 $param3 -Param4 $param4
      shell: pwsh